### ISSUE TITLE
same episode name - owerwrite

### ISSUE THREAD

**Issue by gyandoo** [swappyison/JiocinemaDownloader#14]
hi, i am using jio.sh, however sometimes the episode names are identical when naming the file it igrnoes `.2` for example

[https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3576499](https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3576499)
[https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3657613](https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3657613)
[https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3683822](https://www.jiocinema.com/tv-shows/bigg-boss/13/bigg-boss/3683822)

as a workaround i have put `link_id` in title so the file name is unique 
`title = f'{showName} - S{season_num:02d}E{episode_num:02d} - {episode_title} - {link_id}'`

is there a better way to include parts of an episode so the filename is accurate and the script does not name it as the same file and try to owerwrite

thanks

**Comment by swappyison** [comment]
fixed it

**Comment by gyandoo** [comment]
thank you Sir
