### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by machasundaram** [swappyison/JiocinemaDownloader#3]
Wow you just keep adding to the pile, now an entire show is ripable ! The only thing missing is a custom range( ex. episode-15  to episode-20)

**Comment by swappyison** [comment]
you can run the jioscraper script, it saves all url links in episode_urls.txt, just edit the txt file for what urls you precisely need to download. then run jiobulkdownloader.py

**Comment by machasundaram** [comment]
Thank you for reply. Many minor issues present though, please dont take it as a critism:
1. scrapper saves only last url, and as file name 'episode_url' not '....urls'
2. yt-dlp rsequires '--allow-unplayable-formats' for DRM content
3. pyperclip never used, not a big issue
4. DRM handle not present in bulkdownloader

**Comment by swappyison** [comment]
i am trying to do so, just encountering some issues. Jiodownloader.py script can be iterated with links taken from scraper and yt-dlp with mp4 decrypt plugin be used to both download and decrypt the video.

**Comment by swappyison** [comment]
fixed jioscraper thanks!

**Comment by sarvottam99** [comment]
u fixed the drm part as well??

**Comment by swappyison** [comment]
no I am working on it, currently bulkdownloader only supports DRM free videos.

**Comment by sarvottam99** [comment]
also the txt file generated still is named episode_url.txt instead of episode_urls.txt

**Comment by sarvottam99** [comment]
now just handle the drm part and it will be perfect

**Comment by swappyison** [comment]
jiobulkdownloadDRM is uploaded now, however it needs enter key to be pressed for a new stream everytime. You can use an AHK script to automate that.

**Comment by Abhi5033** [comment]
Hii First of all Thanks for the code.
I tried to download this movie
https://www.jiocinema.com/movies/main-tera-hero/3483383
But is giving only up to 720p. It actually is available in 1080p (coming in TV).
Please check once
