### ISSUE TITLE
English subtitles download

### ISSUE THREAD

**Issue by DeeaM96** [swappyison/JiocinemaDownloader#4]
Hello,

Is there any way to download the english subtitles along the video ?

**Comment by DeeaM96** [comment]
Oooh, that's nice, thank you. I just saw that is directly in the video as a track. 

I was wondering if there is a way to have it as a separate file

**Comment by swappyison** [comment]
i think it's downloaded separately as a file since the mpd of both the video and subtitle urls are different. You can let me know if that's not correct.

**Comment by sarvottam99** [comment]
> Oooh, that's nice, thank you. I just saw that is directly in the video as a track.
> 
> I was wondering if there is a way to have it as a separate file

you can have it as a separate file from the temporary folder while nm3u8dlre downloads the audio and video or u can extract subs from the file after complete process. for example if u use potplayer just press ctrl+shift+s and srt file will be saved in the folder

**Comment by Abhi5033** [comment]
Hii First of all Thanks for the code.
I tried to download this movie
https://www.jiocinema.com/movies/main-tera-hero/3483383
But is giving only up to 720p. It actually is available in 1080p.
Care to check once?
