### ISSUE TITLE
1080p not coming

### ISSUE THREAD

**Issue by Abhi5033** [swappyison/JiocinemaDownloader#5]
Hii Thanks for the code.
I tried to download this movie
https://www.jiocinema.com/movies/main-tera-hero/3483383
The MPD extracted by code is giving only up to 720p. But It is available in 1080p (when played in TV).
Maybe TV API is different? 

Edit: I'm adding MPD link I got for reference

`https://jc-ak-dashstreaming.jiocinema.com/content/entry/wvdata/8/24/0_tr7zep8z_voot_web_premium_1678964315646.mpd?hdnts=st=1693562794~exp=1693563394~acl=/content/entry/wvdata/8/24/*~id=c1b97a18-0e71-47f2-8c43-8d6acf703519~hmac=524844f6efabf6fa9ee194a7e89de4256bf9d12d5c4bb0ae0197f6c3315f6d88`

**Comment by sarvottam99** [comment]
in pc only upto 720p is available

**Comment by Abhi5033** [comment]
How to get 1080p ?

**Comment by sarvottam99** [comment]
try other sources

**Comment by Abhi5033** [comment]
How to grab Android TV api link and headers?

**Comment by swappyison** [comment]
@Abhi5033 use Httptoolkit it can intercept android devices traffic too, grab the mpd. Keys will remain the same.

**Comment by Abhi5033** [comment]
@swappyison Is there a way to automate this token grabbing?
`access_token = input('access_token:')`

**Comment by swappyison** [comment]
I am not sure how to do it, the license url itself expires after a while so making a POST request to retrieve request headers is kind of difficult. Still if there's a method, please let me know i will add it into the script.

**Comment by Abhi5033** [comment]
@swappyison I have few old codes which might help you to find a method. Do u have telegram ?

**Comment by Abhi5033** [comment]
@swappyison Check this one
https://github.com/astravaganza/JC-dl/blob/main/main.py
This author used OTP based login to get token. But this works for old movies only.
